# Generated by Django 4.0 on 2022-01-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
