# Generated by Django 3.2.5 on 2022-01-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_questioncomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioncomment',
            name='body',
            field=models.CharField(max_length=1000),
        ),
    ]
