# Generated by Django 3.2.5 on 2022-01-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_questioncomment_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questioncomment',
            options={'ordering': ('created',)},
        ),
        migrations.AlterField(
            model_name='questioncomment',
            name='body',
            field=models.TextField(),
        ),
    ]
