# Generated by Django 3.2.5 on 2022-01-28 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220128_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questioncomment',
            old_name='question',
            new_name='post',
        ),
    ]
