# Generated by Django 4.0 on 2022-01-29 07:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_rename_question_questioncomment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.CharField(default='anon', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='downvoteList',
            field=models.ManyToManyField(related_name='downvote_count', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='upvoteList',
            field=models.ManyToManyField(related_name='upvote_count', to=settings.AUTH_USER_MODEL),
        ),
    ]
