# Generated by Django 4.0 on 2022-02-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_question_author_question_downvotelist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
    ]
